Лебедев Никита
urfu-2018/javascript-task-1 pull request #13
Opened 2018-10-10 14:57 UTC by qmzik

2018-10-10 14:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 15:07 UTC, honest-hrundel commented
:tomato: Пройдено тестов 60 из 75

2018-10-10 15:10 UTC, honest-hrundel commented
:tomato: Пройдено тестов 61 из 75

2018-10-10 15:13 UTC, honest-hrundel commented
:tomato: Пройдено тестов 63 из 75

2018-10-10 16:46 UTC, honest-hrundel commented
:tomato: Пройдено тестов 64 из 75

2018-10-10 16:51 UTC, honest-hrundel commented
:tomato: Пройдено тестов 64 из 75

2018-10-10 16:55 UTC, honest-hrundel commented
:tomato: Пройдено тестов 64 из 75

2018-10-10 16:59 UTC, honest-hrundel commented
:tomato: Пройдено тестов 66 из 75

2018-10-10 17:10 UTC, honest-hrundel commented
:tomato: Пройдено тестов 66 из 75

2018-10-10 17:14 UTC, honest-hrundel commented
:tomato: Пройдено тестов 69 из 75

2018-10-10 17:28 UTC, honest-hrundel commented
:tomato: Пройдено тестов 68 из 75

2018-10-10 17:29 UTC, honest-hrundel commented
:tomato: Пройдено тестов 68 из 75

2018-10-10 17:32 UTC, honest-hrundel commented
:tomato: Пройдено тестов 69 из 75

2018-10-10 17:38 UTC, honest-hrundel commented
:tomato: Пройдено тестов 69 из 75

2018-10-10 17:41 UTC, honest-hrundel commented
:tomato: Пройдено тестов 69 из 75

2018-10-10 17:45 UTC, honest-hrundel commented
:tomato: Пройдено тестов 70 из 75

2018-10-10 18:00 UTC, honest-hrundel commented
:tomato: Пройдено тестов 70 из 75

2018-10-10 18:06 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 18:08 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 18:11 UTC, honest-hrundel commented
:tomato: Пройдено тестов 70 из 75

2018-10-10 18:13 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 18:16 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 18:18 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 18:24 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 18:25 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 18:27 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 18:33 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 18:34 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 18:37 UTC, honest-hrundel commented
:tomato: Пройдено тестов 70 из 75

2018-10-10 18:39 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 18:56 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 19:14 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 19:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 19:28 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 19:34 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 19:36 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 19:38 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 19:51 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 19:55 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 19:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 20:02 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 20:07 UTC, honest-hrundel commented
:tomato: Пройдено тестов 70 из 75

2018-10-10 20:09 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 20:12 UTC, qmzik commented
🔔 Нужна помощь, не могу найти 4 теста

2018-10-10 20:41 UTC, plotnikovn requested changes

2018-10-10 20:41 UTC, plotnikovn commented on warmup.js
> +    if (field[0][0] === field[1][1] && field[0][0] === field[2][3]) {
кажется, берешь не существующий элемент

2018-10-10 20:41 UTC, plotnikovn commented on warmup.js
> +    return Math.trunc(year / 100) + 1;
а почему +1?

2018-10-10 20:51 UTC, qmzik commented on warmup.js
> +    return Math.trunc(year / 100) + 1;
Получается что 21-ый век в 2000 году, 16 век в 15000 и т.д.
Хардкод, да?

2018-10-10 20:51 UTC, qmzik commented on warmup.js
> +    if (field[0][0] === field[1][1] && field[0][0] === field[2][3]) {
Упс, спасибо большое!

2018-10-10 20:53 UTC, honest-hrundel commented
:tomato: Пройдено тестов 73 из 75

2018-10-10 20:54 UTC, plotnikovn commented on warmup.js
> +    if (!Number.isFinite(n) || !Number.isInteger(targetNs)) {
это лишняя проверка

2018-10-10 20:54 UTC, plotnikovn commented on warmup.js
> +    return regExp.test(phoneNumber) && phoneNumber.length === 15;
ты уже в RegExp указал сколько и чего должно быть, на длину можно не проверять

2018-10-10 20:55 UTC, plotnikovn commented on warmup.js
> +    return Math.trunc(year / 100) + 1;
2000 год это ещё 20 век

2018-10-10 20:58 UTC, honest-hrundel commented
:tomato: Пройдено тестов 73 из 75

2018-10-10 20:59 UTC, qmzik commented on warmup.js
> +    if (!Number.isFinite(n) || !Number.isInteger(targetNs)) {
В состоянии паранойи наставил уже подобные проверки, убрал лишнее

2018-10-10 21:05 UTC, qmzik commented on warmup.js
> +    return Math.trunc(year / 100) + 1;
Аааа, вот оно как, спасибо!

2018-10-10 21:10 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 21:12 UTC, qmzik commented on warmup.js
> +    return Math.trunc(year / 100) + 1;
Исправил!

2018-10-10 21:12 UTC, plotnikovn commented on warmup.js
> +    if (year % 100 === 0) {
можно использовать не `Math.trunc` и убрать эту проверку ;)

2018-10-10 21:14 UTC, honest-hrundel commented
:tomato: Пройдено тестов 73 из 75

2018-10-10 21:16 UTC, plotnikovn commented on warmup.js
> -    if (year < 0 || !Number.isInteger(year)) {
почему положительное?

2018-10-10 21:21 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 21:22 UTC, qmzik commented on warmup.js
> -    if (year < 0 || !Number.isInteger(year)) {
* @param {Number} year Год, целое положительное число

2018-10-10 21:23 UTC, qmzik commented on warmup.js
> -    if (year < 0 || !Number.isInteger(year)) {
Ещё в самой первой функции параметры:
 * @param {Number} a Первое целое
 * @param {Number} b Второе целое

Но если делать проверку isInteger для них, то исчезает один тест

2018-10-10 21:33 UTC, qmzik commented on warmup.js
> -    if (year < 0 || !Number.isInteger(year)) {
Поможете обнаружить последний тест? :)

2018-10-11 08:29 UTC, nikshel commented on warmup.js
> -    if (year < 0 || !Number.isInteger(year)) {
@qmzik 
Посмотри внимательней на `fibonacciProblem`
Хорошо ли функция будет работать с большим `n` (40-50+)?

2018-10-11 13:22 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 75 из 75

2018-10-11 13:22 UTC, closed without merging

2018-10-11 13:23 UTC, qmzik commented on warmup.js
> -    if (year < 0 || !Number.isInteger(year)) {
@nikshel и @plotnikovn, спасибо большое!