Юлдашев Кирилл
urfu-2018/javascript-task-1 pull request #7
Opened 2018-10-10 07:20 UTC by anykk

2018-10-10 07:20 UTC, honest-hrundel commented
:tomato: Пройдено тестов 67 из 75

2018-10-10 07:56 UTC, honest-hrundel commented
:tomato: Пройдено тестов 72 из 75

2018-10-10 08:32 UTC, honest-hrundel commented
:tomato: Пройдено тестов 72 из 75

2018-10-10 08:53 UTC, honest-hrundel commented
:tomato: Пройдено тестов 71 из 75

2018-10-10 08:56 UTC, honest-hrundel commented
:tomato: Пройдено тестов 72 из 75

2018-10-10 09:15 UTC, honest-hrundel commented
:tomato: Пройдено тестов 73 из 75

2018-10-10 09:37 UTC, honest-hrundel commented
:tomato: Пройдено тестов 73 из 75

2018-10-10 09:46 UTC, honest-hrundel commented
:tomato: Пройдено тестов 73 из 75

2018-10-10 13:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 13:10 UTC, honest-hrundel commented
:tomato: Пройдено тестов 73 из 75

2018-10-10 13:47 UTC, honest-hrundel commented
:tomato: Пройдено тестов 73 из 75

2018-10-10 14:04 UTC, honest-hrundel commented
:tomato: Пройдено тестов 73 из 75

2018-10-10 15:29 UTC, honest-hrundel commented
:tomato: Пройдено тестов 72 из 75

2018-10-10 15:49 UTC, honest-hrundel commented
:tomato: Пройдено тестов 72 из 75

2018-10-10 15:57 UTC, honest-hrundel commented
:tomato: Пройдено тестов 72 из 75

2018-10-10 16:00 UTC, honest-hrundel commented
:tomato: Пройдено тестов 73 из 75

2018-10-10 16:04 UTC, honest-hrundel commented
:tomato: Пройдено тестов 73 из 75

2018-10-10 16:05 UTC, honest-hrundel commented
:tomato: Пройдено тестов 73 из 75

2018-10-10 16:17 UTC, honest-hrundel commented
:tomato: Пройдено тестов 73 из 75

2018-10-10 16:33 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 17:01 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 17:22 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 17:24 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 17:29 UTC, honest-hrundel commented
:tomato: Пройдено тестов 72 из 75

2018-10-10 17:31 UTC, honest-hrundel commented
:tomato: Пройдено тестов 73 из 75

2018-10-10 17:32 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 17:47 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 17:59 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 18:17 UTC, honest-hrundel commented
:tomato: Пройдено тестов 70 из 75

2018-10-10 18:20 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 18:24 UTC, honest-hrundel commented
:tomato: Хрюнделя очень расстроил твой код

2018-10-10 18:26 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 18:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 18:31 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 18:34 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 18:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 18:44 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 18:49 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 18:56 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 18:57 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 19:03 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 19:14 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-10 19:17 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 19:19 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 19:25 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 19:28 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-10 19:29 UTC, honest-hrundel commented
:tomato: Пройдено тестов 74 из 75

2018-10-11 02:25 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 75 из 75

2018-10-11 07:24 UTC, KIlyaA requested changes

2018-10-11 07:24 UTC, KIlyaA commented on warmup.js
> +    if (typeof year !== 'number') {
Давай избавимся от `if else`, можно написать плоские `if` и читаться будет проще

```
if () {
    throw new Error(...);
}

if () {
    throw new Error(...);
}

return ...;
```

2018-10-11 07:24 UTC, KIlyaA commented on warmup.js
> +    } else if (year < 0 || !Number.isInteger(year)) {
`!Number.isInteger(year)` вряд-ли это условие относится к ошибке `В качестве года передано отрицательное значение!`

2018-10-11 07:24 UTC, KIlyaA commented on warmup.js
> +    if (typeof hexColor !== 'string') {
Давай тоже напишем более плоскую структуру

2018-10-11 07:24 UTC, KIlyaA commented on warmup.js
> +    if (typeof n !== 'number') {
Тоже плоскую структуру условий

2018-10-11 07:24 UTC, KIlyaA commented on warmup.js
> +    } else {
`else` здесь не нужен, только затрудняет чтение

2018-10-11 07:24 UTC, KIlyaA commented on warmup.js
> +        throw new TypeError();
А текст ошибки?

2018-10-11 07:24 UTC, KIlyaA commented on warmup.js
> +        !Array.isArray(matrix[0])) {
а что если `matrix[1]` будет числом?
давай проверим через matrix.every(Array.isArray)

2018-10-11 07:24 UTC, KIlyaA commented on warmup.js
> +    if (typeof n !== 'number' ||
давай плоскую структуру условий

2018-10-11 07:24 UTC, KIlyaA commented on warmup.js
> +        throw new TypeError();
Давай напишем текст ошибки

2018-10-11 07:24 UTC, KIlyaA commented on warmup.js
> +    return (text.match(/\(-:/g) || []).length + (text.match(/:-\)/g) || []).length;
давай как-то вынесем промежуточные вычисления в переменные с осмысленным названием
```
// Может придумаешь более понятные названия
const leftSmiles = text.match(/\(-:/g) || [];
const rightSmiles = text.match(/:-\)/g) || [];

return leftSmiles.length + rightSmiles.length;
```

2018-10-11 07:24 UTC, KIlyaA commented on warmup.js
>  function ticTacToeProblem(field) {
Давай оставим комментарии около условий, иначе трудно понять, что здесь написано

2018-10-11 07:54 UTC, anykk commented on warmup.js
>  function ticTacToeProblem(field) {
Хорошо, ближе к вечеру всё поправлю

2018-10-11 08:20 UTC, Savichev-Igor commented
Эта задача засчитывается без проверки ментора, если все тесты пройдены

2018-10-11 08:20 UTC, closed without merging